import { PREMIUM_API } from './premium-config.js';
const $=s=>document.querySelector(s);
async function api(path,{method='POST',body,token}={}){const r=await fetch(`${PREMIUM_API.url}/rest/v1/rpc/${path}`,{method,headers:{apikey:PREMIUM_API.anonKey,'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:body?JSON.stringify(body):undefined});if(!r.ok)throw new Error(await r.text());return await r.json();}
async function auth(path,body){const r=await fetch(`${PREMIUM_API.url}/auth/v1/${path}`,{method:'POST',headers:{apikey:PREMIUM_API.anonKey,'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j?.msg||j?.message||'登入失敗');return j;}
const getSession=()=>{try{return JSON.parse(localStorage.getItem('relAdminSession')||'null')}catch{return null}};const saveSession=s=>localStorage.setItem('relAdminSession',JSON.stringify(s));const clearSession=()=>localStorage.removeItem('relAdminSession');
async function rpc(name,body={}){let s=getSession();if(!s?.access_token)throw new Error('請重新登入');try{return await api(name,{body,token:s.access_token})}catch(e){if(s?.refresh_token){try{const n=await auth('token?grant_type=refresh_token',{refresh_token:s.refresh_token});saveSession(n);return await api(name,{body,token:n.access_token})}catch{clearSession()}}throw e}}
function showLogin(msg=''){ $('#loginCard').classList.remove('hidden');$('#adminApp').classList.add('hidden');$('#loginMsg').textContent=msg;}
async function enterAdmin(){const s=getSession();if(!s?.access_token)return showLogin();try{const ok=await rpc('is_relationship_admin');if(!ok)throw new Error('這個帳號沒有管理員權限');$('#loginCard').classList.add('hidden');$('#adminApp').classList.remove('hidden');$('#adminEmail').textContent=s.user?.email||'管理員';await refreshAll()}catch(e){showLogin(e.message.includes('not_authorized')?'這個帳號沒有管理員權限。':e.message)}}
$('#loginBtn').onclick=async()=>{const email=$('#email').value.trim(),password=$('#password').value;if(!email||!password){$('#loginMsg').textContent='請輸入 Email 與密碼。';return}$('#loginMsg').textContent='登入中…';try{const s=await auth('token?grant_type=password',{email,password});saveSession(s);await enterAdmin()}catch(e){$('#loginMsg').textContent=e.message}};
$('#logoutBtn').onclick=()=>{clearSession();showLogin('已登出。')};
async function loadStats(){const d=await rpc('admin_relationship_dashboard');const paid=Number(d.paid_unlock??0);$('#sResult').textContent=d.result_view??0;$('#sClick').textContent=d.pay_click??0;$('#sPaid').textContent=paid;$('#sRevenue').textContent=`NT$${(paid*149).toLocaleString('zh-TW')}`;$('#sClickRate').textContent=`點擊率 ${d.click_rate??0}%`;$('#sPaidRate').textContent=`付費率 ${d.paid_rate??0}%`}
function fmt(d){if(!d)return '無期限';return new Date(d).toLocaleDateString('zh-TW')}
async function loadCodes(){const rows=await rpc('admin_list_relationship_codes');const box=$('#codesList');box.innerHTML='';const pending=rows.filter(r=>r.active&&Number(r.used_count||0)<Number(r.max_uses||1)).length;const used=rows.filter(r=>Number(r.used_count||0)>0).length;$('#sPending').textContent=pending;$('#sUsed').textContent=used;if(!rows.length){box.innerHTML='<p class="muted">目前還沒有建立解鎖碼。</p>';return}rows.forEach(r=>{const el=document.createElement('div');el.className='codeRow';el.innerHTML=`<div><b>${r.label||'未命名客人'}</b><div class="meta">${r.active?'啟用中':'已停用'} ・ 已使用 ${r.used_count}/${r.max_uses} ・ 到期 ${fmt(r.expires_at)} ・ 建立 ${fmt(r.created_at)}</div></div><button class="ghost ${r.active?'danger':'ok'}">${r.active?'停用':'重新啟用'}</button>`;el.querySelector('button').onclick=async()=>{if(!confirm(`確定要${r.active?'停用':'重新啟用'}這組代碼？`))return;await rpc('admin_set_relationship_code_active',{p_id:r.id,p_active:!r.active});await refreshAll()};box.appendChild(el)})}
async function refreshAll(){await Promise.all([loadStats(),loadCodes()])}
$('#generateBtn').onclick=async()=>{const label=$('#codeLabel').value.trim(),max=Number($('#maxUses').value||1),date=$('#expiresAt').value;$('#generateMsg').textContent='產生中…';$('#newCodeBox').classList.add('hidden');try{const d=await rpc('admin_generate_relationship_code',{p_label:label||null,p_max_uses:Math.max(1,max),p_expires_at:date?`${date}T23:59:59+08:00`:null});$('#newCode').textContent=d.code;$('#newCodeBox').classList.remove('hidden');$('#generateMsg').textContent='已建立。請現在複製並傳給客人；重新整理後不會再次顯示明碼。';$('#codeLabel').value='';await refreshAll()}catch(e){$('#generateMsg').textContent='建立失敗：'+e.message}};
$('#copyBtn').onclick=async()=>{await navigator.clipboard.writeText($('#newCode').textContent);$('#copyBtn').textContent='已複製 ✓';setTimeout(()=>$('#copyBtn').textContent='複製代碼',1500)};
$('#refreshBtn').onclick=refreshAll;
enterAdmin();
